
"""A table representing dice rolls as keys with
their associated equipment pieces as values. Also
an additional table with the items as keys and
the cost of those items as values."""

class equipmentTable:
    rollTable = {1: 'Backpack',
                 2: 'Candle',
                 3: '10ft Chain',
                 4: 'Chalk, 1pc',
                 5: 'Chest',
                 6: 'Crowbar',
                 7: 'Flask',
                 8: 'Flint & Steel',
                 9: 'Grappling hook',
                 10: 'Hammer, small',
                 11: 'Holy symbol',
                 12: 'Holy water, 1 vial',
                 13: 'Iron spikes',
                 14: 'Lantern',
                 15: 'Mirror, hand-sized',
                 16: 'Oil, 1 flask',
                 17: 'Pole, 10ft',
                 18: 'Rations',
                 19: 'Rope, 50ft',
                 20: 'Sack, large',
                 21: 'Sack, small',
                 22: 'Thieve\'s tools',
                 23: 'Torch',
                 24: 'Waterskin'}

    costTable = {'Backpack': '2gp',
                 'Candle': '1cp',
                 '10ft Chain': '30gp',
                 'Chalk, 1pc': '1cp',
                 'Chest': '2gp',
                 'Crowbar': '2gp',
                 'Flask': '3cp',
                 'Flint & Steel': '15cp',
                 'Grappling hook': '1gp',
                 'Hammer, small': '5sp',
                 'Holy symbol': '25gp',
                 'Holy water, 1 vial': '25gp',
                 'Iron spikes': '1sp',
                 'Lantern': '10gp',
                 'Mirror, hand-sized': '10gp',
                 'Oil, 1 flask': '2sp',
                 'Pole, 10ft': '15cp',
                 'Rations': '5cp',
                 'Rope, 50ft': '25cp',
                 'Sack, large': '12cp',
                 'Sack, small': '8cp',
                 'Thieve\'s tools': '25gp',
                 'Torch': '1cp',
                 'Waterskin': '5sp'}