from Dice import Dice


class luckScoreTable:
    table = {1:'Harsh Winter: All attack rolls',
             2: 'Taurus: Melee attack rolls',
             3: 'Fortunate Date: Missile attack rolls',
             4: 'Raised by Wolves: Unarmed attack rolls',
             5: 'Conceived on horseback: Mounted attack rolls',
             6: 'Born on the battlefield: Damage rolls',
             7: 'Path of the bear: Melee damage rolls',
             8: 'Hawkeye: Missile fire damage rolls',
             9: 'Pack Hunter: Attach and damage rolls for 0-level trained weapon',
             10: 'Born under the loom: Skill checks (including thievery)',
             11: 'Fox\'s cunning: Find and disable traps',
             12: 'Four-leafed clover: Find secret doors',
             13: 'Seventh Son: Spell checks',
             14: 'The raging storm: Spell damage',
             15: 'Righteous Heart: Turn unholy checks',
             16: 'Survived the plague: Magical healing',
             17: 'Lucky sign: Saving throws',
             18: 'Guardian Angel: Saving throws to escape traps',
             19: 'Survived a Spider Bite: Saving throws against poison',
             20: 'Struck by Lightning: Reflex saving throws',
             21: 'Lived through famine: Fortitude Saving throws',
             22: 'Resisted temptation: Willpower saving throws',
             23: 'Charmed house: Armor class',
             24: 'Speed of the Cobra: Initiative',
             25: 'Bountiful Harvest: Hit points (applies at each level)',
             26: 'Warrior\'s arm: Critical hit luck modifier doubled',
             27: 'Unholy house: Corruption rolls',
             28: 'The Broken Star: Fumble luck modifier doubled',
             29: 'Birdsong: Number of languages',
             30: 'Wild Child: Speed (each +1 = +5 speed)'}
